name: LifeGS
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch::pytorch=2.5.1
  - pytorch::pytorch-cuda=12.1
  - pytorch::torchvision=0.20.1
  - numpy<2
  - scipy<1.14
  - matplotlib
  - tqdm
  - pyyaml
  - pillow
  - pip
  - pip:
    - -r requirements.txt
